### ISSUE TITLE
Error while downloading Youtube Video

### ISSUE THREAD

**Issue by Finnlife** [probablykasper/vidl#3]
When I try to download a Video there occurs the following Error:
![image](https://user-images.githubusercontent.com/26007800/113521779-f6eb0900-959b-11eb-8202-a84bc96871cb.png)
I also made an Issue at yt-dlc, but the author isn't answering for 3 months:
https://github.com/blackjack4494/yt-dlc/issues/305

**Comment by kasper9n** [comment]
I actually meant to switch back from youtube-dlc to youtube-dl in 3.6.1, but forgot to use my brain cells for that. Should be fixed in 3.6.2.
